---
title: "Assignment 1: Introduction"
author: "Jenn McNeill"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project" (If you don't see this option, try restarting RStudio.)


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I do not have any experience with R nor with Git. I have experience with data analytics in Matlab and Excel. In college we used Matlab to analyze data for my engineering classes, and as a full-time engineer I did all of my data analytics in Excel. It has been a long time since I used Matlab, so I do not remember much about how it worked; that being said, I remember thinking that it was an incredibly useful tool.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident in my ability to follow specific instructions and have good attention to detail as I work through learning everything in the course. I also feel confident in my ability to give this class my all and come out of it with a brand new set of skills of which I never imagined myself to be capable.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about my ability to work alone without specific guidance. I also feel apprehensive about solving any technical issues that may arise for me, as I do not have any experience with solving issues by myself through trial and error.


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/jennmcneill/EDE_Fall2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
